In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import time 

In [2]:
X,y = load_diabetes(return_X_y=True)


In [3]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [6]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [7]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568969

In [8]:
class GDRegressor:
    def __init__(self,learing_rate= 0.01, epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learing_rate
        self.epochs = epochs

    def fit(self, X_train, y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            y_hat = np.dot(X_train , self.coef_) + self.intercept_
            intercept_der = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_  - (self.lr * intercept_der)
            coef_der = -2 * np.dot((y_train - y_hat), X_train)/X_train.shape[0]
            self.coef_ = self.coef_ - (self.lr * coef_der)

        print(self.intercept_, self.coef_)
        pass

    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [9]:
gdr = GDRegressor(epochs = 1000, learing_rate=0.5)

In [10]:
start = time.time()
gdr.fit(X_train,y_train)
print('The time taken is', time.time()-start)

152.01351687661833 [  14.38990585 -173.7235727   491.54898524  323.91524824  -39.32648042
 -116.01061213 -194.04077415  103.38135565  451.63448787   97.57218278]
The time taken is 0.018293380737304688


In [11]:
y_pred = gdr.predict(X_test)

In [12]:
r2_score(y_test,y_pred)

0.4534503034722803

In [13]:
class SGDRegressor:
    def __init__(self,learing_rate= 0.01, epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learing_rate
        self.epochs = epochs

    def fit(self, X_train, y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx = np.random.randint(0,X_train.shape[0])
                y_hat = np.dot(X_train[idx] , self.coef_) + self.intercept_
                intercept_der = -2 * (y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)      
                coef_der = -2 * np.dot((y_train[idx] - y_hat), X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
                
        print(self.intercept_, self.coef_)
        
        pass
        
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [14]:

sgd = SGDRegressor(learing_rate=0.01 , epochs=40)

In [15]:
start = time.time()
sgd.fit(X_train,y_train)
print('The time taken is', time.time()-start)

148.37366313422788 [  58.28423625  -51.0868356   322.47915481  224.46671066   26.24438199
  -15.84933842 -163.84252489  128.13249957  295.81217209  125.16817512]
The time taken is 0.11512064933776855


In [16]:
y_pred = sgd.predict(X_test)


In [17]:
r2_score(y_test,y_pred)

0.4212668952743064

In [18]:
from sklearn.linear_model import SGDRegressor


In [19]:
reg = SGDRegressor(max_iter=100, learning_rate='constant',eta0 = 0.01)

In [20]:
reg.fit(X_train,y_train)

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1608: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(learning_rate='constant', max_iter=100)

In [21]:
SGDRegressor(learning_rate='constant', max_iter=100)

SGDRegressor(learning_rate='constant', max_iter=100)

In [22]:
y_pred = reg.predict(X_test)

In [23]:
r2_score(y_test,y_pred)

0.43200484239417636

# mini Batch

In [24]:
import random

In [25]:
class MBGDRegressor:
    def __init__(self,batch_size,learing_rate= 0.01, epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learing_rate
        self.epochs = epochs
        self.batch_size = batch_size

    def fit(self, X_train, y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            for j in range(int(X_train.shape[0]/self.batch_size)):

                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                y_hat = np.dot(X_train[idx] , self.coef_) + self.intercept_
                
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_  - (self.lr * intercept_der)
                
                coef_der = -2 * np.dot((y_train[idx] - y_hat), X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)

        print(self.intercept_, self.coef_)
        pass

    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [26]:
mbr = MBGDRegressor(batch_size= int(X_train.shape[0]/10),learing_rate=0.01, epochs=50)

In [27]:
mbr.fit(X_train, y_train)

152.74611959878305 [  49.85431585  -62.37780618  351.87156472  254.03420453   16.37115823
  -33.15310038 -166.72109905  120.16049906  323.07811029  131.66120587]


In [28]:
y_pred = mbr.predict(X_test)

In [29]:
r2_score(y_test,y_pred)

0.43286165812647037

In [30]:
from sklearn.linear_model import SGDRegressor

In [31]:
sgd = SGDRegressor(learning_rate = 'constant', eta0 = 0.1)

In [32]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [33]:
sgd.coef_

array([  52.99345958, -101.76065416,  358.99881206,  248.93985856,
         38.1176206 ,  -12.17148083, -166.30535981,  121.85357997,
        324.16838296,  105.82758656])

In [34]:
sgd.intercept_

array([181.88213061])

In [35]:
y_pred

array([154.7832534 , 192.8277027 , 140.38442202, 110.52883428,
       245.65480672, 236.04953577, 109.82341011, 116.02178996,
        94.92133511, 185.55015555, 161.44504862, 173.0304965 ,
       184.15287719, 149.87794996, 254.68732794,  94.449355  ,
       186.02208954, 141.13990708, 141.49192996, 140.03606575,
       134.11265786, 189.48370456, 165.61519079, 178.81950276,
       127.98973704, 218.56906752, 196.30985889, 121.0897771 ,
        63.90805134, 240.80311252, 234.64019987, 119.92111037,
        76.04107519, 111.16935062, 200.8032139 , 165.41482575,
       168.01750565, 195.88876122, 116.36201173, 232.71363105,
       138.06074386, 128.56483834, 185.30089773, 186.807292  ,
       171.01843288, 146.69173355, 174.2252116 , 277.57336406,
       118.69517314, 187.85157906, 238.46731476, 131.35221433,
       144.52489089, 149.16816797, 190.42764463, 114.18899539,
       155.05504408,  87.88729581, 159.50792399, 144.44800378,
       164.75422759, 170.98270227, 111.72339273, 206.04

In [36]:
r2_score(y_test,y_pred)

0.43286165812647037